export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CATALOG_ROUTE = '/'
export const LIKED_ROUTE = '/likes'
export const FILM_ROUTE = '/film'
export const MOVIE_ROUTE = '/movie'